// Import statements
import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import lightBulb from "../../public/images/svgs/aY.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light '>
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image
                src={profilePic}
                alt="Ayaz Memon"
                width={500}
                height={500}
                className='w-full h-auto'
                priority
                sizes="(max-widht: 768px) 100vw,
                (max-widht:1200px) 50vw,
                50vw"
              />
            </div>
            <div className='w-1/2 flex-col items-center self-center'>
              <AnimatedText text="Turning Vision Into Reality With React..." className='text-6xl text-dark' />
              <p className='my-4 text-base font-medium'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link
                  href="/Ayaz Memon CV.pdf"
                  target="_blank"
                  download
                  className="flex items-center bg-dark text-light p-2.5 px-5 rounded-full text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light 
                  hover:dark:border-light"
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <div className="ml-4"> {/* Added margin to create gap */}
                  <Link href="mailto:ayazsmemon07@gmail.com" target="_blank">
                    <button className="bg-dark text-light py-2.5 px-5 rounded-full font-semibold shadow-md hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark transition-colors duration-300 dark:text-light">
                      Contact
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Layout>

        <div className='absolute right-10 bottom-8 inline-block w-20'>
          <Image
            src={lightBulb}
            alt="Lightbulb"
            width={100}
            height={100}
            className='w-full h-auto'
          />
        </div>
      </main>
    </>
  );
}
